### ISSUE TITLE
Работа отдельных фрагментов кода

### ISSUE THREAD

**Issue by Alexandr010360** [tesanoff/midibayan#1]
Здравствуйте Александр! Меня очень заинтересовал ваш проект! Особенно структура кода! Всё упорядочено, по полочкам и системно! Хотел позаимствовать у вас управление клавиатурой через сдвиговые регистры 74HC165. Даже сделал макет фрагмента кода из трёх кнопок. Но к сожалению он не заработал. Вы не смогли бы набросать мне фрагмент кода касающийся клавиатуры, который бы работал автономно и передавал миди команды.

**Comment by tesanoff** [comment]
Добрый день.
к 6-й ноге ардуинки подключен каскад, читающий левую клавиатуру. [здесь задан этот пин](https://github.com/tesanoff/midibayan/blob/211e6babf87a316b51ede85d33aca2efe7c3e462/tes_midi_bayan/TesKeyboard.cpp#L81)

Смотрите как читается левая клавиатура.

В интернете очень много информации о том, как читать данные из сдвиговых регистров. (Если проблема именно с чтением данных из регистров). Соберите простейшую схему на макетке и тренируйтесь, как я делал: https://tesanoff.klah.ru/?p=5414

**Comment by Alexandr010360** [comment]
Благодарю Александр! Теперь увидел замок! Буду пробовать! А что касается простейшего макета работы с регистрами то у меня это всё работает.

**Comment by tesanoff** [comment]
Класс TesKeyboard читает данные с регистров, смотрит какие "музыкальные" кнопки были нажаты (или отпущены) и на основании этой информации помещает во внутреннюю очередь сообщений сообщения о соответствующих событиях. Только этот класс знает, что есть 2 каскада регистров, и т.д.

Класс TesMIDIController получает эти сообщения из внутренней очереди и обрабатывает (посылает соответствующие миди команды.) Миди-контроллер не знает ничего о деталях реализации чтения клавиатуры. Он знает только о том, что есть 107 музыкальных кнопок, которые кто-то-там читает и присылает ему сообщения об их нажатиях.

**Comment by Alexandr010360** [comment]
На портe Ардуино D6 указан сигнал Kbd-DATA2 и есть разъём J6. Но на остальных схемах я не нашёл этого сигнала замка! Откуда он поступает?

**Comment by Alexandr010360** [comment]
На схеме левой клавиатуры есть разъём J1 и на нём сигнал data-out. Это он?

**Comment by tesanoff** [comment]
> На схеме левой клавиатуры есть разъём J1 и на нём сигнал data-out. Это он?

Так точно
J1 с платы левой клавиатуры соединяется с J6 на основной плате.

Latch и CLK идут одновременно и к правой и к левой клавиатуре.

**Comment by tesanoff** [comment]
И ещё момент: эта прошивка не заработает нормально, если не подключен экранчик. Зависнет на этапе инициализации экранчика.

**Comment by Alexandr010360** [comment]
Всё понял! Благодарю за информацию!

**Comment by Alexandr010360** [comment]
Тема закрыта!

**Comment by Alexandr010360** [comment]
Собрал макет из двух регистров сдвига и шести кнопок! Подаю питание, инициализация проходит нормально! Импульсы Latch и CLK присутствуют! Но только соит нажать одну из шести кнопок проскакивает один импульс Kbd-DATA и ардуинка намертво зависает! Latch и CLK пропадают! Сбрасываю её кнопкой сброса на плате и повторяется тоже самое! Отключаю от ардуинки входы Kbd-DATA  и она начинает работать нормально! Kbd-DATA на 9 ножках регистров при нажатии любой из кнопок имеются! Но стоит их подсоединить к ардуинке то она перестаёт работать!

**Comment by Alexandr010360** [comment]
С другой ардуинкой тоже самое! Загружаю тестовый код работы регистров сдвига и с ним всё отлично работает!

**Comment by Alexandr010360** [comment]
![d2f939ea-ee89-4998-8baf-fc0241e48fee](https://github.com/user-attachments/assets/f113c2b0-e086-4a61-90eb-bd98011e65fe)

**Comment by Alexandr010360** [comment]
Фто макета прилагаю...

**Comment by tesanoff** [comment]
Извините, я с вашей бедой вам помочь не могу.
Могу только пожелать успехов в поиске причины такого поведения вашего макета.

**Comment by Alexandr010360** [comment]
Спасибо Александр! Уже разобрался! Я брал по одному регистру на левую и правую клавиатуру! В этом случае сигнал переноса на 10 выводе регистра должен быть притянут к питанию! А я этого не сделал! А при каскадном включении нескольких регистров сигнал переноса приходит с предыдущего регистра с 9 ножки!

**Comment by Alexandr010360** [comment]
Uploading WhatsApp Video 2024-10-27 at 19.11.52.mp4…

**Comment by Alexandr010360** [comment]
Uploading WhatsApp Video 2024-10-27 at 19.11.52.mp4…

**Comment by Alexandr010360** [comment]
https://github.com/user-attachments/assets/d49b1244-3ceb-4390-b175-83d8c6913b7b

**Comment by Alexandr010360** [comment]
Вот результат! Тему закрываю!

**Comment by tesanoff** [comment]
Ишь ты.
Даже какие-то звуки издаёт. :)

**Comment by Alexandr010360** [comment]
Это у меня работает через виртуальный мост Hairless MIDI<->Serial Bridge! А с него уже идёт на программный секвенсор...

**Comment by tesanoff** [comment]
Кстати, я обратил внимание, что есть очень заметная задержка между щелчком кнопки и звуком инструмента.

Видимо это из-за не самого быстродействующего софта.

Я подключался к VMPK (на Линуксе) https://sourceforge.net/projects/vmpk/
Вообще никаких задержек не слышно.

**Comment by Alexandr010360** [comment]
С задержками уж потом как нибудь разберусь! В моих проектах вроде не замечал задержек! Главное макет заработал! Теперь нужно это всё адаптировать для гармони. Ваш проект гармонь не готов ещё?

**Comment by tesanoff** [comment]
Адаптация для гармони делается здесь: https://gitflic.ru/project/tesanoff/midi-garmon
Еще не готово.
Точнее говоря, схемы уже нарисованы, платы заказаны и едут к хозяину гармони. Проверки на реальном железе пока не было. Когда будет готово - сделаю релиз на Gitflic и возможно сделаю зеркало на github.

**Comment by Alexandr010360** [comment]
Благодарю за ваш огромный труд! Пытался сам адаптировать прошивку под гармонь! Но как говорят чужая прошивка для меня пока тёмный лес! Долго нужно изучать что к чему! Я в основном использую для своих прошивок готовые миди библиотеки. Комбинирую и соединяю классы которые мне нужны! А с нуля писать пока ещё не умею. Так как недавно начал в этом разбираться! Тем более я не программист а инженер конструктор в области электроники. А сейчас просто пенсионер. Программирование ардуино это моё хобби! Осваиваю потихоньку...

**Comment by Alexandr010360** [comment]
Я тоже сейчас скачал и подключал  VMPK. Задержка стала меньше! Дело в драйвере звуковой карты. Тем более подключение не через миди кабель а по UART. Для опытов нормально. А потом можно подключиться по стандартному протоколу через миди кабель к внешней звуковой карте. Там задержки вообще незаметны на слух!

**Comment by tesanoff** [comment]
Да, в windows не самая быстрая MIDI поддержка...

**Comment by Alexandr010360** [comment]
Добрый день Александр! Читал ваш блог и планы на будущее! Желаю вам успехов! Планы поистине грандиозные! Идея с SD-картой мне понравилась! Вот бы можно было с карты проигрывать стили автоаккомпанимента а не только жёстко запрограммированный ритм! Так же можно было бы гибко менять и конфигурацию оборудования. Назначать функции клавиш и кнопок управления. Назначать горячие клавиши чтобы менять на ходу во время исполнения песни разные эффекты, тембры, стили автоаккомпанимента! У меня есть исходники по этой теме. Могу поделиться! Зачем велосипед изобретать заново, когда его уже изобрели... Куда вам отправить папку с файлами? Посмотрите опытным вглядом программиста! Может что то и найдёте ценное для ваших будущих проектов!

**Comment by Alexandr010360** [comment]
`/*
    BLE_MIDI_HARMONICA
*/

#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>
#include <BLE2902.h>
#include "notes.h"
#include "keyboards.h"

#define CHANNEL0 0
#define CHANNEL1 1
#define CHANNEL2 2

#define SERVICE_UUID        "03b80e5a-ede8-4b33-a751-6ce34ec4c700"
#define CHARACTERISTIC_UUID "7772e5db-3868-4112-a1a9-f2669d106bf3"

const byte LATCH = 25;
const byte DATA  = 26;
const byte CLOCK = 14;

BLECharacteristic *pCharacteristic;
bool deviceConnected = false;

class MyServerCallbacks: public BLEServerCallbacks {
    void onConnect(BLEServer* pServer) {
      deviceConnected = true;
    };

    void onDisconnect(BLEServer* pServer) {
      deviceConnected = false;
    }
};

void setupBle() {
  BLEDevice::init("MIDI HARMONICA");
  BLEServer *pServer = BLEDevice::createServer();
  pServer->setCallbacks(new MyServerCallbacks());
  BLEService *pService = pServer->createService(BLEUUID(SERVICE_UUID));
  pCharacteristic = pService->createCharacteristic(
                      BLEUUID(CHARACTERISTIC_UUID),
                      BLECharacteristic::PROPERTY_READ   |
                      BLECharacteristic::PROPERTY_WRITE  |
                      BLECharacteristic::PROPERTY_NOTIFY |
                      BLECharacteristic::PROPERTY_WRITE_NR
                    );
  pCharacteristic->addDescriptor(new BLE2902());
  pService->start();
  BLEAdvertising *pAdvertising = pServer->getAdvertising();
  pAdvertising->addServiceUUID(pService->getUUID());
  pAdvertising->start();
}

void setupKeyboard() {
  pinMode(LATCH, OUTPUT);
  pinMode(CLOCK, OUTPUT);
  pinMode(DATA, INPUT);
  digitalWrite(LATCH, HIGH);
}

uint64_t readKeyboard() {
  digitalWrite(LATCH, LOW);
  digitalWrite(LATCH, HIGH);

  byte buffer[8];
  for ( int i = 0; i < 8; i++) {
    buffer[i] = shiftIn(DATA, CLOCK, MSBFIRST);
  }

  uint64_t states = 0;
  for ( int i = 7; i >= 0; i--) {
    states <<= 8;
    states |= (uint64_t) buffer[i];
  }
  return states;
}

void noteOn(BLECharacteristic *midiDevice, uint8_t note, uint8_t channel) {
  uint8_t channels[3] = { 0x90, 0x91, 0x92 };
  uint8_t midiPacket[] = {
    0x80,               // header
    0x80,               // timestamp, not implemented
    channels[channel],  // action
    note,               // pitch
    127                 // velocity
  };
  midiPacket[2] = channels[channel];    // note down, channel 0
  midiPacket[3] = note;                 // note
  midiPacket[4] = 127;                  // velocity
  midiDevice->setValue(midiPacket, 5);  // packet, length in bytes
  midiDevice->notify();
}

void noteOff(BLECharacteristic *midiDevice, uint8_t note, uint8_t channel) {
  uint8_t channels[3] = { 0x80, 0x81, 0x82 };
  uint8_t midiPacket[] = {
    0x80,               // header
    0x80,               // timestamp, not implemented
    channels[channel],  // action
    note,               // pitch
    0                   // velocity
  };
  midiDevice->setValue(midiPacket, 5);  // packet, length in bytes
  midiDevice->notify();
}

void processKeyboardChanges(uint64_t keyboard) {
  static uint64_t last_keyboard = 0;
  if (keyboard == last_keyboard) {
    return;
  }
  uint64_t changed = keyboard ^ last_keyboard;
  last_keyboard = keyboard;
  for (int i = 0; i <= 64; ++i)
  {
    if (changed & 1) {
      handleChange(i, keyboard & 1);
    }
    changed >>= 1;
    keyboard >>= 1;
  }
}

void handleChange(int key, int state) {
  uint8_t note = 0;
  uint8_t channel = 0;
  if (key < sizeof(rightKeyboard)) {
    note = rightKeyboard[key];
    channel = CHANNEL0;
  } else if (key >= 32 && key < (32 + sizeof(bassKeyboard))) {
    note = bassKeyboard[key - 32];
    channel = CHANNEL1;
  } else if (key >= 32 + sizeof(bassKeyboard)) {
    note = accordKeyboard[key - 32 - sizeof(bassKeyboard)];
    channel = CHANNEL2;
  } else {
    return;
  }
  if (state) {
    Serial.print("noteOn -> ");
    Serial.println(note);
    Serial.print("channel -> ");
    Serial.println(channel);
    Serial.println("");
    noteOn(pCharacteristic, note, channel);
  } else {
    Serial.print("noteOff -> ");
    Serial.println(note);
    Serial.print("channel -> ");
    Serial.println(channel);
    Serial.println("");
    noteOff(pCharacteristic, note, channel);
  }
}

void setup() {
  Serial.begin(115200);
  setupKeyboard();
  setupBle();
}

void loop() {
  if (deviceConnected) {
    uint64_t keyboard = readKeyboard();
    processKeyboardChanges(keyboard);
  }
}
`

**Comment by tesanoff** [comment]
>  У меня есть исходники по этой теме. Могу поделиться!

спасибо, ничего не надо :)

**Comment by Alexandr010360** [comment]
Всё понял! Извините!

**Comment by tesanoff** [comment]
не за что извиняться, что вы.

Просто я в чужой код стараюсь вообще не лазить, если нет острой необходимости. Применительно к чтению миди-файлов такая необходимость есть (писать своё будет заметно дольше, чем адаптировать чужое), но я уже нашёл шикарный исходник. (см блог)

**Comment by Alexandr010360** [comment]
Хотел бы иногда по возможности обращаться к вам за помощью в некоторых критических ситуациях! Дело в том что я уже два года использую миди библиотеку адаптированную в универсальную панель управления DAW. Эта библиотека имеет возможность расширения и добавление в неё новых функций! Но к сожалению автором уже не поддерживается! Я её переделал под свои нужды и сделал миди гармонь Беларусь. Но там есть не решёные ньюансы. Один из них это отстсутствие поддержки регистров сдвига! Пришлось всё делать на матрицах. И второй ньюанс это отображение на дисплее не названий программ, а их номеров в миди системе, как и в вашем коде! Ну это ладно, как то можно смириться! Но вот во второй версии моей гармони, предназначеной к совместной работе с DAW vAranger это недопустимо! В этом проекте кнопки панели управления программно привязаны к параметрам DAW. И я должен видеть полное отображение на дисплее этих параметров, когда я нажимаю одну из кнопок панели управления! А их 30 штук! Цифры тут никак не уместны! А параметры настроек и управление DAW вот они: 
  1 TRANSPOSE -
  2 TRANSPOSE +
  3 PREV S0NG
  4 NEXT SONG
  5 TEMPO -
  6 TEMPO +
  7 MANUAL BASS
  8 BASS TO LOWEST
  9 SECUND BOICE
  10 FULL KEYBOARD
  11 MY S0UND RIGHT 1
  12 MY S0UND RIGHT 2
  13 MY S0UND RIGHT 3
  14 MY S0UND RIGHT 4
  15 MY S0UND RIGHT 5
  16 MY SOUND LEFT 1
  17 MY SOUND LEFT 2
  18 MY SOUND LEFT 3
  19 MY SOUND LEFT 4
  20 MY SOUND LEFT 5
  21 START/STOP
  22 SYNG START
  23 INTRO 1
  24 INTRO 2
  25 INTRO 3
  26 ENDING 1
  27 ENDING 2
  28 ENDING 3
  29 VARIATION DOWN
  30 VARIATION UP

**Comment by tesanoff** [comment]
а в чем сам вопрос?

**Comment by Alexandr010360** [comment]
Матрицы заменить на регистры сдвига и параметры кнопок управления отобразить на дисплее! Вот и ломаю голову как это сделать...

**Comment by Alexandr010360** [comment]
Это нужно ворошить библиотеку или просто в код добавить классы дисплея и регистров сдвига...

**Comment by Alexandr010360** [comment]
Знаний в программировании недостаточно...

**Comment by tesanoff** [comment]
> Матрицы заменить на регистры сдвига

Если честно, не понял.

"Регистр сдвига" - это микросхемы которые, например, я использовал для ввода кнопок и вывода на светодиоды 74HC165 и 74HC595.
А "матрица" - это что?

**Comment by Alexandr010360** [comment]
Матричная клавиатура как на первом баяне Александра Поликарпова...столбцы и строки на пересечении которых стоят датчики холла или кнопки...

**Comment by tesanoff** [comment]
а-а-а. Понял.
Замену этой системы ввода на ввод через регистры я уже сделал. :)

Читайте здесь: https://github.com/tesanoff/midibayan#%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%BF%D0%BE%D1%8F%D0%B2%D0%B8%D0%BB%D1%81%D1%8F-%D1%8D%D1%82%D0%BE%D1%82-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82

**Comment by Alexandr010360** [comment]
Так вот по этой причине меня и заинтересовал ваш собственный проект! А вот как это прикрутить к моему коду пока ломаю голову!

**Comment by Alexandr010360** [comment]
Для проекта гармони все порты Ардуино Мега почти заняты! А для баяна вообще уже не хватает портов! Применение в моём проекте регистров сдвига решило бы проблему...

**Comment by Alexandr010360** [comment]
Сделать какой нибудь отдельный класс с регистрами сдвига и прилепить его к моему коду! Пока не знаю как это сделать!

**Comment by tesanoff** [comment]
Ну, берите мою прошивку и дорабатывайте под свои нужды. Я никаких ограничений на эту тему не накладываю.

Возможно, вам стоит взять в соавторы программиста, квалификации которого будет достаточно, чтобы разобраться в коде и придумать, что и как надо менять. (Я не возьмусь, если что).

**Comment by Alexandr010360** [comment]
Вот я и изучаю вашу прошивку! Так то конечно разберусь и без программистов только это будет долгий процесс...
Буду следить за вашими новыми публикациями! Очень интересные у вас идеи! Бутусову и не снились такие идеи со стилями для автоаккомпанимента! Да ещё если отобразить на дисплее название этих стилей!

**Comment by Alexandr010360** [comment]
Как сделать чтобы нажатие одной из множества кнопок на дисплее отображалось её название одной строчкой? В интернете что то не нашёл такого примера кода...

**Comment by tesanoff** [comment]
Если по-нормальному, то надо добавлять ещё один вариант экрана:
* идентификатор статуса экрана
* функция для отрисовки экрана
* функция для обработки нажатий клавиш в этом режиме
* посмотреть не возникает ли нежелательных побочных эффектов

Если для отладки, то:
* чистим экран вызывая функцию clear() если правильно помню
* печатаем на экране всё что надо
* выводим буфера на экран функцией update()
* Даём задержку на пару-тройку секунд, чтобы успеть это прочитать

**Comment by Alexandr010360** [comment]
Спасибо Александр за инструкцию! Буду пробовать...
