### ISSUE TITLE
Смена дисплея на SSD1306_128x64

### ISSUE THREAD

**Issue by Alexandr010360** [tesanoff/midibayan#2]
Добрый день Александр! У меня в наличии дисплей SSD1306_128x64. В скетче меняю SSH1106_128x64 на SSD1306_128x64! Но компилятор начинает ругаться! Помогите пожалуйста разобраться в проблеме...

**Comment by Alexandr010360** [comment]
![e667875c-ebeb-4429-962e-4bf0a5845fbc](https://github.com/user-attachments/assets/d7666746-c811-4105-a6c2-1c23d4987152)

**Comment by Alexandr010360** [comment]
Вот такие крякозябры с моим дисплеем!

**Comment by tesanoff** [comment]
Документацию на библиотеку изучали? https://github.com/GyverLibs/GyverOLED
(Особенно разделы "Инициализация" и "Использование")

Работу примеров (https://github.com/GyverLibs/GyverOLED/tree/main/examples) на вашем экране проверяли?

**Comment by Alexandr010360** [comment]
Примеры все работают нормально! Использовал эту библиотеку в других своих проектах. Там всё отлично работает.

**Comment by Alexandr010360** [comment]
Ядро я не менял. Может быть в этом дело? И вообще с кнопками работает очень не стабильно. С холлами не пробовал.

**Comment by Alexandr010360** [comment]
Попробую сейчас ядро поменять...

**Comment by tesanoff** [comment]
Проверяйте, во всех ли местах используется правильная инициализация класса дисплея.
В прошивке несколько таких мест.
Используйте команду "grep GyverOLED *"

**Comment by tesanoff** [comment]
> И вообще с кнопками работает очень не стабильно.

Если это макетка, то:
1) контакты
2) висящие в воздухе входы регистров

**Comment by Alexandr010360** [comment]
Все места посмотрел! И менял на другой дисплей. свободные входы регистров заземлил...

**Comment by Alexandr010360** [comment]
А у вас нет такой возможности проверить с другим дисплеем ваш код?

**Comment by Alexandr010360** [comment]
Придётся тогда купить дисплей SSH1106_128x64...

**Comment by tesanoff** [comment]
Ну, чудес не бывает.
Ищите разницу между тем, что сейчас в прошивке, и тем, что в работающих примерах.
Покажите пример того, как вы инициализируете класс. Прям кусок вашего кода.

**Comment by Alexandr010360** [comment]
Там не кусок кода. Я загрузил полностью вашу прошивку...

**Comment by tesanoff** [comment]
Я на своей стороне ничего отлаживать для других дисплеев не могу.

**Comment by tesanoff** [comment]
> Там не кусок кода. Я загрузил полностью вашу прошивку...

Тип дисплея не меняли? Неудивительно что не работает.

Если меняли, то покажите измененный участок кода :)

**Comment by Alexandr010360** [comment]
GyverOLED<SSH1106_128x64> oled; Все эти места менял...

**Comment by Alexandr010360** [comment]
Может текст ошибки вам отправить?

**Comment by Alexandr010360** [comment]
GyverOLED<SSD1306_128x64, OLED_NO_BUFFER> oled; Если только ещё так попробовать?

**Comment by Alexandr010360** [comment]
В примерах если раскомментировать вот это GyverOLED<SSH1106_128x64> oled; То так же вылезают крякозябры как и в вашей прошивке...

**Comment by tesanoff** [comment]
> GyverOLED<SSH1106_128x64> oled; Все эти места менял...

именно такие места надо было менять.
Покажите ваш вариант кода который получился после того, как вы поменяли тип дисплея.

Если это не секрет. :)

**Comment by Alexandr010360** [comment]
А если раскомментировать вот это GyverOLED<SSD1306_128x64, OLED_NO_BUFFER> oled; То дисплей работает нормально...

**Comment by Alexandr010360** [comment]
Дело в том что в библиотеке и настраивать то нечего! А делаю как в примерах не работает!

**Comment by Alexandr010360** [comment]
Я имею ввиду с вашим кодом...

**Comment by Alexandr010360** [comment]
Не получается самому разобраться в вашей прошивке! Это автор только может...

**Comment by Alexandr010360** [comment]
Буду дальше изучать код! Может что ещё увижу...

**Comment by Alexandr010360** [comment]
Может ядро как то влияет?

**Comment by Alexandr010360** [comment]
Да ладно! На Озоне есть такие дисплеи как ваш. Закажу и вопрос закрыт...

**Comment by tesanoff** [comment]
> А если раскомментировать вот это GyverOLED<SSD1306_128x64, OLED_NO_BUFFER> oled; То дисплей работает нормально...

Так всё-таки работает дисплей или не работает?

В любом случае мне надо видеть код с вашим вариантом инициализации дисплея. Я не могу вслепую комментировать.
Пожалуйста, покажите тот код инициализации дисплея, который у вас сейчас.
И скажите, работает дисплей с таким вариантом инициализации или нет.

Жду кода.

**Comment by Alexandr010360** [comment]
В примерах библиотеки работает а в вашем коде нет. Буду искать в чём причина...

**Comment by Alexandr010360** [comment]
Собственно код ваш без изменения! Менял только это во всех файлах кода где он есть GyverOLED<SSD1306_128x64, OLED_NO_BUFFER> oled;

**Comment by tesanoff** [comment]
> Собственно код ваш без изменения! Менял только это во всех файлах кода где он есть GyverOLED<SSD1306_128x64, OLED_NO_BUFFER> oled;

И в результате заработало или нет?

(Вообще, лучше выбрать вариант с буфером.)

**Comment by Alexandr010360** [comment]
// OLED-дисплей
GyverOLED<SSD1306_128x64, OLED_NO_BUFFER> oled;

// MIDI-контроллер
TesMIDIController   theMIDIController(&ledSet, &oled); - ругается на это!

**Comment by tesanoff** [comment]
> TesMIDIController theMIDIController(&ledSet, &oled); - ругается на это!

Правильно, потому что менять нужно везде, где встречается строка "GyverOLED<", а не только в одном месте.
Это же темплейтный класс.

**Comment by Alexandr010360** [comment]
Вот я и менял везде! Сейчас по ходу покажу...
 

                                                     ^

**Comment by Alexandr010360** [comment]
Теперь на это ругается // Конструктор
TesMIDIController::TesMIDIController(TesLedSet *led_panel, GyverOLED<SSD1306_128x64, OLED_NO_BUFFER> *oled)
    :_ui(oled, this, led_panel),
    _auto_drums(&_midi_queue)

**Comment by Alexandr010360** [comment]
Ещё раз проверю и напишу что получилось...

**Comment by tesanoff** [comment]
Везде (вообще везде) где встречается такая строчка:
`GyverOLED<SSH1106_128x64>`

её надо заменить на такую:
`GyverOLED<SSD1306_128x64, OLED_BUFFER>`

Вообще везде, даже если вам кажется что в каком-то конкретном месте менять не надо.

И должно скомпилиться и заработать.

**Comment by Alexandr010360** [comment]
![0644e846-c2b2-4ef0-a965-4b8295ae16d8](https://github.com/user-attachments/assets/0d790356-89ea-4682-adee-d29138be13ce)
Везде поменял а потом стал компилировать! Вроде грузится! Я неправильно делал! Одну заменю компилирую. Потом дальше. Следующую. А нужно было всё заменить а потом компилировать! Но инициализация дисплея не прошла! Потому что я его вытащил! Сейчас поставлю на место и скомпилирую...

**Comment by Alexandr010360** [comment]
![Uploading 0644e846-c2b2-4ef0-a965-4b8295ae16d8.jpg…]()

**Comment by tesanoff** [comment]
Отлично!

**Comment by Alexandr010360** [comment]
Спасибо Александр за помощь и терпение! Сам бы мог разобраться! Просто подсуетился немного...

**Comment by Alexandr010360** [comment]
Теперь буду пробовать с датчиками холла! Кнопки глючат!

**Comment by tesanoff** [comment]
> Кнопки глючат!

Вообще, не должно быть никакой разницы между кнопками и датчиками. Я на таких же кнопках отлаживался, как у вас: https://rutube.ru/video/8d49a0cc3f9e7e1af202a5c735093099/?r=wd

**Comment by Alexandr010360** [comment]
Очень странные глюки идут по тактовому сигналу на выводе 2 регистра! Пока держишь на нём щуп осциллографа тактовая частота есть. Как только убрал и через некоторое время она пропадает. Нажимаю кнопку сброса на Ардуино и она появляется, потом обратно пропадает. Так же импульс защёлки пропадает вместе с частотой!

**Comment by Alexandr010360** [comment]
На Меге у меня так никогда не было!

**Comment by Alexandr010360** [comment]
Завтра буду пробовать на Ардуино UNO...

**Comment by Alexandr010360** [comment]
По дисплею тему закрываю! А что касается неустойчивой работы Ардуино Нано будет другая тема.

**Comment by Alexandr010360** [comment]
Тема по дисплею закрыта.
