### ISSUE TITLE
Замена ядра Ардуино Нано с целью оптимизации ресурсов микроконтролера

### ISSUE THREAD

**Issue by Alexandr010360** [tesanoff/midibayan#3]
Пытался заменить ядро следуя инструкции. Но к сожалению ничего не получилось. В окне Ардуино IDE пишет что нет такого протокола! Буду пытаться ставить ядро другими методами.

**Comment by Alexandr010360** [comment]
Что в этой ссылке не так? https://alexgyver.github.io/package_GyverCore_index.json

**Comment by Alexandr010360** [comment]
Что в этой ссылке не так? https://alexgyver.github.io/package_GyverCore_index.json

**Comment by Alexandr010360** [comment]
Все методы испытал! Ничего не получилось!

**Comment by tesanoff** [comment]
Ну, я не самый большой специалист по Adruino IDE.
К тому же я не под Windows работаю, а под Linux.
В принципе можно и без ядра, просто свободной памяти заметно меньше останется и код будет немного медленнее работать.

**Comment by tesanoff** [comment]
https://community.alexgyver.ru/  здесь попробуйте помощи попросить.

**Comment by Alexandr010360** [comment]
Вопрос о ядре я поднял только потому что при компиляции прошивки выскакивает предупреждение недостаточно памяти! И что из-за этого возможно нестабильная работа прошивки. Хотел заменить ядро чтобы освободить ещё немного памяти. Может поэтому у меня глючит Ардуино Ноно? Что интересно она глючила и с первой прошивкой Александра Поликарпова! У него тоже вся память была забита! Поэтому и хочу разобраться в причине глюков методом экспериментов. А кнопки тут не причём, я выяснил. Пропадают сигналы Kbd-CLK и Kbd-Latch. Может быть потому что подключена только часть схемы на макете! А делать сразу на готовых платах это риск и лишние затраты! Хотелось бы убедиться в работоспособности и стабильности макета. Мои собственные проекты на макете работают стабильно. У меня все входы и выходы фильтруются программно! А на регистрах сдвига такую фильтрацию не применишь...

**Comment by Alexandr010360** [comment]
Собственно вопрос в том что я не хочу применять матричную систему клавиатуры как в моих проектах по причине потребления датчиками холла тока опасного для портов Ардуино! Паспортный максимальный ток одного вывода 40 миллиампер! А одновременно открытые к примеру 8 датчиков холла уже перегружают порт Ардуино!

**Comment by Alexandr010360** [comment]
Ладно, спасибо что откликнулись на мой запрос! Надеюсь разберусь. Тему закрываю...

**Comment by tesanoff** [comment]
> Вопрос о ядре я поднял только потому что при компиляции прошивки выскакивает предупреждение недостаточно памяти!

У меня тоже выскакивает. Это нормально и ожидаемо. если есть хотя бы 150 байт свободных - должнго работать нормально, я стек не сильно нагружаю.

>  А делать сразу на готовых платах это риск и лишние затраты! 

Что мешает сделать макет на 1 или 2 регистра и отладочный вариант прошивки?
Я весь баян написал и отладил используя только 6 кнопок. :)

**Comment by Alexandr010360** [comment]
Буду разбираться почему пропадают тактовые сигналы с Ардуино Нано...

**Comment by tesanoff** [comment]
заменить ее и всё
она стоит не так много

**Comment by tesanoff** [comment]
Или другой пин использовать

**Comment by Alexandr010360** [comment]
Вот я и попробую её заменить. А пока она идёт по заказу испытаю этот макет с Ардуино UNO...

**Comment by Alexandr010360** [comment]
Переустановил программу Arduino IDE и загрузил новое ядро! Экономия памяти значительная! Оперативки осталось ещё 1163 байта! Но глюки так и остались! Буду менять Ардуину!
